// Generated by gencpp from file xv_sdk/PoseStampedConfidence.msg
// DO NOT EDIT!


#ifndef XV_SDK_MESSAGE_POSESTAMPEDCONFIDENCE_H
#define XV_SDK_MESSAGE_POSESTAMPEDCONFIDENCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace xv_sdk
{
template <class ContainerAllocator>
struct PoseStampedConfidence_
{
  typedef PoseStampedConfidence_<ContainerAllocator> Type;

  PoseStampedConfidence_()
    : confidence(0.0)
    , poseMsg()  {
    }
  PoseStampedConfidence_(const ContainerAllocator& _alloc)
    : confidence(0.0)
    , poseMsg(_alloc)  {
  (void)_alloc;
    }



   typedef double _confidence_type;
  _confidence_type confidence;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _poseMsg_type;
  _poseMsg_type poseMsg;





  typedef boost::shared_ptr< ::xv_sdk::PoseStampedConfidence_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xv_sdk::PoseStampedConfidence_<ContainerAllocator> const> ConstPtr;

}; // struct PoseStampedConfidence_

typedef ::xv_sdk::PoseStampedConfidence_<std::allocator<void> > PoseStampedConfidence;

typedef boost::shared_ptr< ::xv_sdk::PoseStampedConfidence > PoseStampedConfidencePtr;
typedef boost::shared_ptr< ::xv_sdk::PoseStampedConfidence const> PoseStampedConfidenceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xv_sdk::PoseStampedConfidence_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xv_sdk::PoseStampedConfidence_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xv_sdk::PoseStampedConfidence_<ContainerAllocator1> & lhs, const ::xv_sdk::PoseStampedConfidence_<ContainerAllocator2> & rhs)
{
  return lhs.confidence == rhs.confidence &&
    lhs.poseMsg == rhs.poseMsg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xv_sdk::PoseStampedConfidence_<ContainerAllocator1> & lhs, const ::xv_sdk::PoseStampedConfidence_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xv_sdk

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xv_sdk::PoseStampedConfidence_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xv_sdk::PoseStampedConfidence_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xv_sdk::PoseStampedConfidence_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xv_sdk::PoseStampedConfidence_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xv_sdk::PoseStampedConfidence_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xv_sdk::PoseStampedConfidence_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xv_sdk::PoseStampedConfidence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e08d1c3f683917c5bb4ba335dd8b604";
  }

  static const char* value(const ::xv_sdk::PoseStampedConfidence_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e08d1c3f683917cULL;
  static const uint64_t static_value2 = 0x5bb4ba335dd8b604ULL;
};

template<class ContainerAllocator>
struct DataType< ::xv_sdk::PoseStampedConfidence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xv_sdk/PoseStampedConfidence";
  }

  static const char* value(const ::xv_sdk::PoseStampedConfidence_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xv_sdk::PoseStampedConfidence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 confidence\n"
"geometry_msgs/PoseStamped poseMsg\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::xv_sdk::PoseStampedConfidence_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xv_sdk::PoseStampedConfidence_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.confidence);
      stream.next(m.poseMsg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseStampedConfidence_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xv_sdk::PoseStampedConfidence_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xv_sdk::PoseStampedConfidence_<ContainerAllocator>& v)
  {
    s << indent << "confidence: ";
    Printer<double>::stream(s, indent + "  ", v.confidence);
    s << indent << "poseMsg: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.poseMsg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XV_SDK_MESSAGE_POSESTAMPEDCONFIDENCE_H
